ARG POSTGRES_VERSION=17
FROM postgres:${POSTGRES_VERSION}

# Install OpenSSL, sudo, and pgvector
RUN apt-get update && apt-get install -y openssl sudo postgresql-17-pgvector \
    && rm -rf /var/lib/apt/lists/*

# Allow the postgres user to execute certain commands as root without a password
RUN echo "postgres ALL=(root) NOPASSWD: /usr/bin/mkdir, /bin/chown, /usr/bin/openssl" > /etc/sudoers.d/postgres

# Add init scripts while setting permissions
COPY --chmod=755 ./postgres/init-ssl.sh /docker-entrypoint-initdb.d/init-ssl.sh
COPY --chmod=755 ./postgres/wrapper.sh /usr/local/bin/wrapper.sh

ENTRYPOINT ["wrapper.sh"]
CMD ["postgres", "-p", "5432", "-c", "listen_addresses=*"]
