[options]
addons_path = $ADDONS_PATH
admin_passwd = $ADMIN_PASSWD
csv_internal_sep = ,
data_dir = $DATA_DIR
db_host = $DB_HOST
db_maxconn = $DB_MAXCONN
db_name = $DB_NAME
db_password = $DB_PASSWORD
db_port = $DB_PORT
db_sslmode = $DB_SSLMODE
db_template = $DB_TEMPLATE
db_user = $DB_USER
dbfilter = $DBFILTER
email_from = $EMAIL_FROM
from_filter =
geoip_city_db = /usr/share/GeoIP/GeoLite2-City.mmdb
http_enable = True
http_interface =
http_port = $PORT
import_partial =
limit_memory_hard = $LIMIT_MEMORY_HARD
limit_memory_soft = $LIMIT_MEMORY_SOFT
limit_request = $LIMIT_REQUEST
limit_time_cpu = $LIMIT_TIME_CPU
limit_time_real = $LIMIT_TIME_REAL
limit_time_real_cron = -1
list_db = $LIST_DB
log_db =
log_db_level = warning
log_handler = $LOG_HANDLER
log_level = $LOG_LEVEL
logfile = $LOG_FILE
logrotate = $LOG_ROTATE
gevent_port = $WS_PORT
max_cron_threads = $MAX_CRON_THREADS
pg_path =
pidfile =
proxy_mode = $PROXY_MODE
reportgz = False
screencasts =
screenshots = /tmp/odoo_tests
server_wide_modules = base,web
smtp_password = $SMTP_PASSWORD
smtp_port = $SMTP_PORT
smtp_server = $SMTP_HOST
smtp_ssl = $SMTP_SSL
smtp_ssl_certificate_filename =
smtp_ssl_private_key_filename =
smtp_user = $SMTP_USER
syslog = False
test_enable = False
test_file =
test_tags =
transient_age_limit = 1.0
unaccent = $UNACCENT
upgrade_path =
with_demo = $WITHOUT_DEMO
workers = $WORKERS
